Merlin Pass/force-app/main/default/objects/Pass__c/Pass__c.object-meta.xml
<CustomObject>
    <description>This object is used to store pass detail</description>
    <label>Pass</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Pass Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Related Customer Record</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passes</relationshipLabel>
    <relationshipName>Passes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Date_Of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Travel__c</fullName>
    <formula>Customer__r.Expected_Date_Of_Travel__c</formula>
    <label>Date Of Travel</label>
    <type>Date</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Expected_Weather__c.field-meta.xml
<CustomField>
    <fullName>Expected_Weather__c</fullName>
    <description>This shows expected weather dates on dates of travel</description>
    <inlineHelpText>This shows expected weather dates on dates of travel</inlineHelpText>
    <label>Expected Weather</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

Merlin Pass/force-app/main/default/classes/GetPass.cls
@RestResource(urlMapping = '/GetPassDetails')
global class GetPass {
    @HttpPost 
    global static Pass__c getPassData(String mailOrPhoneNumber)
    {
        Pass__c passToReturn = [SELECT Id,Name,Order_Date__c, Date_Of_Travel__c, Customer__r.Name,
        Customer__r.Email, Customer__r.Age__c, Customer__r.MobilePhone, Expected_Weather__c 
        FROM Pass__c
        WHERE Customer__r.Email = :mailOrPhoneNumber OR Customer__r.MobilePhone =: mailOrPhoneNumber];
        return passToReturn;
    }
}