Merlin Pass/force-app/main/default/objects/Pass__c/Pass__c.object-meta.xml
<CustomObject>
    <description>This object is used to store pass detail</description>
    <label>Pass</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Pass Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Passes</relationshipLabel>
    <relationshipName>Passes</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>This is used to hold the successful payment record for a success</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Bill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Payment__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field which connect the pass to payment</description>
    <label>Pass</label>
    <referenceTo>Pass__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/classes/PassTriggerHelper.cls
public with sharing class PassTriggerHelper {
    public static List<Payment__c> updatePayment(List<Pass__c> listOfPasses) {
        Set<Id> setOfIds = new Set<Id>();
        Map<Id,Pass__c> mapOfPaymentIdToPass = new Map<Id,Pass__c>();
        for(Pass__c passObj : listOfPasses) {
            mapOfPaymentIdToPass.put(passObj.Payment__c, passObj);
        }
        List<Payment__c> listOfPayments;
        if(!mapOfPaymentIdToPass.isEmpty()) {
            listOfPayments = [SELECT Id, Pass__c FROM Payment__c WHERE Id =: mapOfPaymentIdToPass.keySet()];
        }
        if(!listOfPayments.isEmpty()) {
            for(Payment__c pay : listOfPayments) {
                pay.Pass__c = mapOfPaymentIdToPass.get(pay.Id).Id;
            }
            update listOfPayments;
        }
        return listOfPayments;
    }
}