Merlin Pass/force-app/main/default/objects/Pass__c/Pass__c.object-meta.xml
<CustomObject>
    <description>This object is used to store pass detail</description>
    <label>Pass</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Pass Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Passes</relationshipLabel>
    <relationshipName>Passes</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>This is used to hold the successful payment record for a success</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Bill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Payment__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field which connect the pass to payment</description>
    <label>Pass</label>
    <referenceTo>Pass__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/classes/PassTriggerHandler.cls
public with sharing class PassTriggerHandler {
    public static void afterInsert(List<Pass__c> listOfNewPassObject) {
        List<Pass__c> listOfPassToProcess = new List<Pass__c>();
        for(Pass__c passObj : listOfNewPassObject) {
            if(passObj.Payment__c != null) {
                listOfPassToProcess.add(passObj);
            }
        }
        PassTriggerHelper.updatePayment(listOfPassToProcess);
    }
}