Merlin Pass/force-app/main/default/objects/Attraction__c/Attraction__c.object-meta.xml
<CustomObject>
    <description>This is used to store attraction data and related details</description>
    <label>Attraction</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Attraction__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Field To Hold Address of Attraction</description>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Attraction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field to hold attraction description</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Attraction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Field to hold geolocation of the location to show on map</description>
    <label>Location</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Attraction__c/fields/Location_Image__c.field-meta.xml
<CustomField>
    <fullName>Location_Image__c</fullName>
    <description>field to hold image of location</description>
    <label>Location Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/AttractionPass__c/AttractionPass__c.object-meta.xml
<CustomObject>
    <description>This object act as a junction between attraction and pass and facilitates many to many relationship</description>
    <label>AttractionPass</label>
    <nameField>
        <label>AttractionPass Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AttractionPasses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/AttractionPass__c/fields/Attraction__c.field-meta.xml
<CustomField>
    <fullName>Attraction__c</fullName>
    <description>Lookup field for Related Attraction Record</description>
    <label>Attraction</label>
    <referenceTo>Attraction__c</referenceTo>
    <relationshipLabel>AttractionPasses</relationshipLabel>
    <relationshipName>AttractionPasses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/AttractionPass__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <description>Lookup field with link to attached pass record</description>
    <label>Pass</label>
    <referenceTo>Pass__c</referenceTo>
    <relationshipLabel>AttractionPasses</relationshipLabel>
    <relationshipName>AttractionPasses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Pass__c/Pass__c.object-meta.xml
<CustomObject>
    <description>This object is used to store pass detail</description>
    <label>Pass</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Pass Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Related Customer Record</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Passes</relationshipLabel>
    <relationshipName>Passes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Pass__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Passes</relationshipLabel>
    <relationshipName>Passes</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>This is used to hold the successful payment record for a success</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Bill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Merlin Pass/force-app/main/default/objects/Payment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>This acts as related field for the customer reocrd</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Merlin Pass/force-app/main/default/objects/Payment__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field which connect the pass to payment</description>
    <label>Pass</label>
    <referenceTo>Pass__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Merlin Pass/force-app/main/default/classes/AttractionsController.cls
public with sharing class AttractionsController {
    @AuraEnabled(Cacheable=true)
    public static List<AttractionsWrapper> getAttractions(){
        List<AttractionsWrapper> listOfAttractionsWrapper = new List<AttractionsWrapper>();
        AttractionsWrapper attrWrapperObj;
        try {
            List<Attraction__c> listOfAttractions = [SELECT Id, Name, Description__c,Address__c, 
            Location_Image__c, Location__c, Price__c,Short_Description__c FROM Attraction__c];
            for(Attraction__c attr : listOfAttractions) {
                attrWrapperObj = new AttractionsWrapper();
                attrWrapperObj.attractionObj = attr;
                attrWrapperObj.isSelected = false;
                listOfAttractionsWrapper.add(attrWrapperObj);
            }
            return listOfAttractionsWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id generatePass(Id conId, Id paymentId, List<Attraction__c> listOfAttraction){
        try {
            AttractionPass__c junctionAttrPass;
            List<Pass__c> listOfPassToInsert = new List<Pass__c>();
            List<AttractionPass__c> listOfAttractionPass = new List<AttractionPass__c>();
            Pass__c passToInsert = new Pass__c();
            passToInsert.Customer__c = conId;
            passToInsert.Payment__c = paymentId;
            listOfPassToInsert.add(passToInsert);
            if(!listOfPassToInsert.isEmpty()){
                insert listOfPassToInsert;
            }
            
            if(!listOfAttraction.isEmpty()) {
                for(Attraction__c attr : listOfAttraction) {
                    junctionAttrPass = new AttractionPass__c();
                    junctionAttrPass.Attraction__c = attr.Id;
                    junctionAttrPass.Pass__c = passToInsert.Id;
                    listOfAttractionPass.add(junctionAttrPass);
                }
            }
            if(!listOfAttractionPass.isEmpty()) {
                insert listOfAttractionPass;
            }
            return passToInsert.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    class AttractionsWrapper {
        @AuraEnabled
        public Attraction__c attractionObj{get;set;}
        @AuraEnabled
        public Boolean isSelected{get;set;}
    }
}